### ISSUE TITLE
Error when executing git-meld-index

### ISSUE THREAD

**Issue by lprobsth** [jjlee/git-meld-index#3]
git: 2.35.1
meld: 3.18.0

after installing git-meld-index and running it either with `git meld-index` or directly with `git-meld-index` it throws the following error:

```/home/lprobsth/.local/bin/git-meld-index-run-merge-tool: 282: /home/lprobsth/.local/bin/git-meld-index-run-merge-tool: diff_cmd: not found```

**Comment by lprobsth** [comment]
I installed git version 2.17.1 and git-meld-index worked in this version.

I think that `diff_cmd` is needed by git-mergetool--lib (https://github.com/git/git/blob/78a26cb7204ddb96a5f75f09e41fbefd81c85f59/git-mergetool--lib.sh#L282).

**Comment by jjlee** [comment]
I haven't been using this for some time but I tried to fix it up on branch `master`.  Does that work for you?  It now depends on Python 3 and I'm using git 2.35.1

**Comment by jjlee** [comment]
I just pushed a better fix for something I hacked 3 weeks ago, having now actually understood what was going on with the case of unmerged files (merge/rebase conflicts).  It's on branch `master` still.

I believe it should be working fine again now, would be great if you could give it a try.

**Comment by jjlee** [comment]
Fix released in 0.2.3

**Comment by lprobsth** [comment]
Sorry for the late answer - I tested your new version and can confirm that it is normally working on my system.

Thank you very much!
